# Generated by Django 3.0.6 on 2020-06-21 10:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='Application_name',
            field=models.CharField(blank=True, max_length=40),
        ),
        migrations.AlterField(
            model_name='reseller',
            name='Application_name',
            field=models.CharField(blank=True, max_length=40),
        ),
    ]
