# Generated by Django 3.0.6 on 2020-07-08 05:21

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_auto_20200621_1204'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customer',
            name='customer_domain',
        ),
        migrations.RemoveField(
            model_name='customer',
            name='customer_email',
        ),
        migrations.RemoveField(
            model_name='reseller',
            name='reseller_domain',
        ),
        migrations.RemoveField(
            model_name='reseller',
            name='reseller_email',
        ),
        migrations.AddField(
            model_name='profile',
            name='domain',
            field=models.CharField(default=django.utils.timezone.now, max_length=40, unique=True),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='profile',
            name='email',
            field=models.EmailField(blank=True, max_length=70),
        ),
        migrations.AddField(
            model_name='profile',
            name='logo',
            field=models.ImageField(blank=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='customer',
            name='Application_name',
            field=models.CharField(max_length=40, unique=True),
        ),
        migrations.AlterField(
            model_name='reseller',
            name='Application_name',
            field=models.CharField(max_length=40, unique=True),
        ),
    ]
